package biblioteca.vista;

public enum Opcion {
SALIR,INSERTAR_USUARIO,BORRAR_USUARIO,MOSTRAR_USUARIO,INSERTAR_LIBRO,BORRAR_LIBRO,MOSTRAR_LIBROS, NUEVO_PRESTAMO,
    DEVOLVER_PRESTAMO, MOSTRAR_PRESTAMOS, MOSTRAR_PRESTAMOS_USUARIOS
}
